# Generated by Django 5.0.6 on 2024-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdata',
            name='delay',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='jitter',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
