# Generated by Django 5.0.6 on 2024-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_linkdata_delay_alter_linkdata_jitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdata',
            name='delay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='jitter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
